spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: dd-MM-yyyy
  datasource:
    url: jdbc:mysql://localhost:3306/todos
    username: todos-user
    password: dummytodos
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

