INSERT INTO TODO (ID, USERNAME, DESCRIPTION, DATE, IS_DONE)
VALUES (1000, 'rajasekhar2307', 'Todo number one', CURRENT_DATE(), false);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, DATE, IS_DONE)
VALUES (1001, 'rajasekhar2307', 'Todo number two', CURRENT_DATE(), false);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, DATE, IS_DONE)
VALUES (1002, 'rajasekhar2307', 'Todo number three', CURRENT_DATE(), false);